### ISSUE TITLE
Double click on filetree won't open files anymore

### ISSUE THREAD

**Issue by zhigang1992** [ChrisRM/material-theme-jetbrains#1481]
### Summary

Double click to open on file tree stopped working with the latest version of Webstorm and Material UI

### Environment

```
WebStorm 2019.3.1
Build #WS-193.5662.54, built on December 18, 2019
Licensed to Kyle Fang
You have a perpetual fallback license for this version
Subscription is active until June 24, 2021
Runtime version: 11.0.5+10-b520.17 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.2
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: IdeaVIM, com.chrisrm.idea.MaterialThemeUI, com.deadlock.scsyntax, com.google.idea.bazel.ijwb, com.intellij.lang.jsgraphql, luonq.ScrollFromSource, oorg.bvic23.intellij.plugin.storybook.Storybook, org.toml.lang, ru.adelf.idea.dotenv
```

**Comment by mallowigi** [comment]
What do you mean double click to open? I’ve been using the plugin for a while now and didn’t encounter any issues. Can you tell me the steps?

**Comment by Querencia** [comment]
I have that same problem. When I double-click any file on the left side of the project files, some files won't open.

**Comment by yaorc911** [comment]
> What do you mean double click to open? I’ve been using the plugin for a while now and didn’t encounter any issues. Can you tell me the steps?

**Summary**
    I also encountered this problem after updating the plugin. Double click a python file in a project often does not open. 
    I pushed the plugin back to version 4.11.0 to open the file properly.

**Environment**

- Material Theme UI Plugin 4.11.4
- PyCharm 2019.3.1 Pro
- Python 3.7
- Win10 1909

**Comment by webcoderkz** [comment]
WebStorm 2019.3.1 had the same issue with 4.11.4, downgraded to 4.11.0 as @yaorc911 and i can open files with double click again. It's a critical bug.

**Comment by mallowigi** [comment]
Please give me more information. Is it specific files? Folders ? Do you have auto scroll to source? Which os? I’ve checked this morning and could not reproduce.

**Comment by Eroppo** [comment]
Also having this issue, but was thinking it's PyCharm 2019.3 bug)) After reading this issue checked disabling Material Theme - without plugin it works as intended. 

> Please give me more information. Is it specific files? Folders ? Do you have auto scroll to source? Which os? I’ve checked this morning and could not reproduce.

The problem is now you have to double click the filename directly to open this file, double clicking anywhere in the line of this file does nothing instead of opening it. Tried to show on screenshot:
![dblclick](https://user-images.githubusercontent.com/13285107/71256257-407cf980-2341-11ea-84d7-64d5fd13d7b2.jpg)

**Comment by alx-khramov** [comment]
I have similar issue last few days after updates of WebStorm to 2019.3 and the plugin (don't remember the exact version, I updated to 4.11.4 since then, the issue is still here).
But it just looks like you can't open files with double click. In fact you can, but you must click exactly on the name of the file, not on the area near the file. Also the bug is only with files, the opening of directories is ok.

**Comment by mallowigi** [comment]
I see, I’ll check why is that happening. I’m always clicking on the file that explains why I haven’t got it.

I’m on hiatus for now after 4 hotfix so it will take some time. You can go back on 4.11 for now

**Comment by CrazyCoder** [comment]
https://youtrack.jetbrains.com/issue/IDEA-229884
https://youtrack.jetbrains.com/issue/WEB-43051

**Comment by mallowigi** [comment]
@Crazycoder do you know someone from jetbrains who can pinpoint me to the right direction? I did everything I could but could not make it work. It looks like something hardcoded in the source code related to DefaultTreeUI

**Comment by CrazyCoder** [comment]
@mallowigi you can contact Sergey.Malenkov@jetbrains.com or submit your specific question at https://intellij-support.jetbrains.com/hc/en-us/community/topics/200366979-IntelliJ-IDEA-Open-API-and-Plugin-Development.

**Comment by mallowigi** [comment]
Sergey helped me and I got it fixed. It will be available next release.
