### ISSUE TITLE
Turns function names to black color in pycharm

### ISSUE THREAD

**Issue by kumaranvpl** [ChrisRM/material-theme-jetbrains#174]
I installed this theme in pycharm version 2016.1. After restarting while the indexing bar is still loading in the bottom of pycharm, the functions/files opened in editor looks as usual. This is how it starts while index is loading

![normal](https://cloud.githubusercontent.com/assets/7011056/14076214/758c9264-f4fd-11e5-9e18-faa5b774c73e.png)

But after the indexing is finished, the function names opened in editor turns to black. All the color schemes changes to some weird color. Below is the reference screenshot.

![odd](https://cloud.githubusercontent.com/assets/7011056/14076249/bb294ede-f4fd-11e5-8443-087b0b0e1bfa.png)

This error also happens with [material peacock](https://github.com/daylerees/material-peacock) too. But this issue is not coming if I install same theme in phpstorm or rubymine.

**Comment by uunbound** [comment]
I have the same issue on latest PyCharm on OSX.

**Comment by tycoles** [comment]
Same problem here. I'm running it on Ubuntu 16.04 under the gnome desktop environment.

**Comment by Neo23x0** [comment]
Same problem here.

**Comment by zhoujiealex** [comment]
Same problem with latest pycharm 2016.1.2

I upgrade from 4.5 to latest version. And the function name becomes black which is ugly

**Comment by zhoujiealex** [comment]
hi @kumaranvpl  have you solved this issue?

**Comment by MohamedWasim** [comment]
How to change the Background to Black?
It's White in my case>?

**Comment by kumaranvpl** [comment]
Nope 👎  @zhoujiealex

**Comment by heyoni** [comment]
I think if you turn off inspections and restart pycharm it fixes it...obviously not ideal

**Comment by nitaidean** [comment]
There is a solution, easy fix. This guy figured it out at the link below

https://intellij-support.jetbrains.com/hc/en-us/community/posts/203369290-All-colour-themes-set-my-function-definitions-black-

**Comment by mallowigi** [comment]
should be fixed in the latest release

**Comment by anishchadayappan** [comment]
Using 2018 Pycharm the issue still persists

**Comment by nikita-kiryanov** [comment]
I also have this issue

**Comment by ScoobyQ** [comment]
Issue persists in latest pycharm AFAICS

**Comment by starwarswii** [comment]
still happens. similar to what's mentioned here https://github.com/ChrisRM/material-theme-jetbrains/issues/174#issuecomment-245907144 it's temporarily fixed by turning **on** inspections. for some reason when inspections are off, the bug occurs.

any level works. so if you don't really want to see inspections, turn them on to e.g. `Highlight: Syntax` which won't show very much, unlike the default level of `Highlight: All Problems`
