### ISSUE TITLE
Font text is garbled

### ISSUE THREAD

**Issue by jasonhebert** [ChrisRM/material-theme-jetbrains#957]
### Summary

PHPStorm UI presented with illegible text in +95% of areas after Windows 10 October update.

### Expected behavior

UI Text should be clear, correct, and readable.

### Actual behavior

Majority of the UI text presented is illegible and presented in a fashion that cannot be read. Screenshots attached.

### Steps to reproduce (if needed)

1. Have the Material Theme UI plugin enabled in PHPStorm
2. Update Windows 10 to the October Cumulative Update 1803
3. Start PHPStorm
4. Notice PHPStorm UI is illegible

![phpstorm_ui_borked](https://user-images.githubusercontent.com/4276690/46424041-add14a00-c6fd-11e8-89c3-3942ccb08bc2.png)

The following errors were reported by the application:

```
java.lang.Throwable: Icon cannot be found in '/javaee/application_xml.svg', aClass='class com.intellij.icons.AllIcons$Javaee'
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:134)
	at com.intellij.openapi.util.IconLoader.getIcon(IconLoader.java:157)
	at com.intellij.openapi.util.IconLoader.getIcon(IconLoader.java:118)
	at com.intellij.icons.AllIcons$Javaee.<clinit>(AllIcons.java:1600)
	at com.intellij.execution.update.UpdateRunningApplicationAction.<init>(UpdateRunningApplicationAction.java:25)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.intellij.util.ReflectionUtil.newInstance(ReflectionUtil.java:419)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:146)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getActionImpl(ActionManagerImpl.java:471)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:459)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.preloadActions(ActionManagerImpl.java:1275)
	at com.intellij.openapi.actionSystem.impl.ActionPreloader.preload(ActionPreloader.java:32)
	at com.intellij.openapi.application.Preloader.lambda$null$0(Preloader.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:583)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:533)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.application.Preloader.lambda$initComponent$1(Preloader.java:63)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:227)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$100(BoundedTaskExecutor.java:26)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2$1.run(BoundedTaskExecutor.java:200)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:229)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
```
Following exceptions happened soon after this one, most probably they are induced.


2018-10-03T11:06:08.683
com.intellij.diagnostic.PluginException: java.lang.reflect.InvocationTargetException [Plugin: com.intellij]
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:149)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getActionImpl(ActionManagerImpl.java:471)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:459)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.preloadActions(ActionManagerImpl.java:1275)
	at com.intellij.openapi.actionSystem.impl.ActionPreloader.preload(ActionPreloader.java:32)
	at com.intellij.openapi.application.Preloader.lambda$null$0(Preloader.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:583)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:533)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.application.Preloader.lambda$initComponent$1(Preloader.java:63)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:227)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$100(BoundedTaskExecutor.java:26)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2$1.run(BoundedTaskExecutor.java:200)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:229)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.intellij.util.ExceptionUtilRt.rethrow(ExceptionUtilRt.java:31)
	at com.intellij.util.ExceptionUtil.rethrow(ExceptionUtil.java:120)
	at com.intellij.util.ReflectionUtil.newInstance(ReflectionUtil.java:427)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:146)
	... 19 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.intellij.util.ReflectionUtil.newInstance(ReflectionUtil.java:419)
	... 20 more
Caused by: java.lang.ExceptionInInitializerError
	at com.intellij.execution.update.UpdateRunningApplicationAction.<init>(UpdateRunningApplicationAction.java:25)
	... 25 more
Caused by: java.lang.IllegalStateException: @NotNull method com/intellij/openapi/util/IconLoader.getIcon must not return null
	at com.intellij.openapi.util.IconLoader.$$$reportNull$$$0(IconLoader.java)
	at com.intellij.openapi.util.IconLoader.getIcon(IconLoader.java:159)
	at com.intellij.openapi.util.IconLoader.getIcon(IconLoader.java:118)
	at com.intellij.icons.AllIcons$Javaee.<clinit>(AllIcons.java:1600)
	... 26 more
```

### Environment

PhpStorm 2018.3 EAP
Build #PS-183.3283.10, built on October 3, 2018
PhpStorm EAP User
Expiration date: November 2, 2018
JRE: 1.8.0_152-release-1343-b3 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
Material Theme UI version v2.10.0
No other non-bundled plugins installed/enabled

[material_theme.txt](https://github.com/ChrisRM/material-theme-jetbrains/files/2442825/material_theme.txt)

**Comment by mallowigi** [comment]
I need to fix those errors, as for the font, try to reinstall the Roboto font from Google Fonts.

**Comment by jasonhebert** [comment]
Reinstalled all Roboto fonts and that fixed the majority of the issues but there are still items remaining in various places. Most buttons still borked, some menu and tree-view items as well.

![phpstorm_ui_present](https://user-images.githubusercontent.com/4276690/46426944-9eee9580-c705-11e8-8a3e-92b70bca5a71.png)

**Comment by mallowigi** [comment]
Did you restart the computer? Otherwise you can try to disable the Material Fonts feature and see if that helps.

**Comment by jasonhebert** [comment]
Restarted and the text issues seem resolved but the plugin is now causing the `JavaScript Support` plugin to throw the following error, disable `Material Theme UI` plugin and no more error:
```
java.lang.NoClassDefFoundError: Could not initialize class com.intellij.icons.AllIcons$Javaee
	at com.intellij.lang.typescript.compiler.TypeScriptToolWindowProvider.<init>(TypeScriptToolWindowProvider.java:33)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:85)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:62)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:45)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:209)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:246)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:213)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:52)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:30)
	at com.intellij.lang.typescript.compiler.TypeScriptToolWindowProvider.getToolWindow(TypeScriptToolWindowProvider.java:25)
	at com.intellij.lang.typescript.compiler.languageService.TypeScriptServerServiceImpl.createToolWindow(TypeScriptServerServiceImpl.java:662)
	at com.intellij.lang.javascript.service.JSAsyncLanguageServiceBase.<init>(JSAsyncLanguageServiceBase.java:43)
	at com.intellij.lang.javascript.service.JSLanguageServiceBase.<init>(JSLanguageServiceBase.java:23)
	at com.intellij.lang.typescript.compiler.TypeScriptCompilerService.<init>(TypeScriptCompilerService.java:132)
	at com.intellij.lang.typescript.compiler.languageService.TypeScriptServerServiceImpl.<init>(TypeScriptServerServiceImpl.java:143)
	at com.intellij.lang.typescript.compiler.languageService.TypeScriptServerServiceImpl.<init>(TypeScriptServerServiceImpl.java:137)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:85)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:62)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:45)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:209)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:246)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:213)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:52)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:30)
	at com.intellij.lang.typescript.compiler.TypeScriptLanguageServiceProvider.getAllServices(TypeScriptLanguageServiceProvider.java:29)
	at com.intellij.lang.javascript.service.JSLanguageServiceProvider.lambda$getLanguageServices$0(JSLanguageServiceProvider.java:24)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.intellij.lang.javascript.service.JSLanguageServiceProvider.getLanguageServices(JSLanguageServiceProvider.java:24)
	at com.intellij.lang.typescript.compiler.TypeScriptCompilerService.getAll(TypeScriptCompilerService.java:105)
	at com.intellij.lang.typescript.compiler.TypeScriptCompilerSettingsTracker.getAdditionalSettings(TypeScriptCompilerSettingsTracker.java:49)
	at com.intellij.lang.typescript.compiler.TypeScriptCompilerSettingsTracker.lambda$new$0(TypeScriptCompilerSettingsTracker.java:31)
	at com.intellij.openapi.util.AtomicNotNullLazyValue$1.compute(AtomicNotNullLazyValue.java:60)
	at com.intellij.openapi.util.AtomicNotNullLazyValue.getValue(AtomicNotNullLazyValue.java:38)
	at com.intellij.lang.typescript.compiler.TypeScriptCompilerSettingsTracker.getModificationCount(TypeScriptCompilerSettingsTracker.java:37)
	at com.intellij.util.CachedValueBase.getTimeStamp(CachedValueBase.java:157)
	at com.intellij.psi.impl.PsiCachedValue.getTimeStamp(PsiCachedValue.java:101)
	at com.intellij.util.CachedValueBase.collectDependencies(CachedValueBase.java:150)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:60)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:87)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:139)
	at com.intellij.lang.typescript.compiler.TypeScriptLanguageServiceAnnotatorCheckerProvider.isAvailable(TypeScriptLanguageServiceAnnotatorCheckerProvider.java:49)
	at com.intellij.lang.javascript.ecmascript6.TypeScriptAnnotatorCheckerProvider.getCheckerProvider(TypeScriptAnnotatorCheckerProvider.java:47)
	at com.intellij.lang.typescript.inspections.TypeScriptUnresolvedFunctionInspection.createVisitor(TypeScriptUnresolvedFunctionInspection.java:39)
	at com.intellij.lang.typescript.inspections.TypeScriptUnresolvedFunctionInspection.createVisitor(TypeScriptUnresolvedFunctionInspection.java:21)
	at com.intellij.lang.javascript.inspections.JSInspection.buildVisitor(JSInspection.java:60)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:53)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:310)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$5(LocalInspectionsPass.java:278)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:126)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:115)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$6(LocalInspectionsPass.java:275)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:133)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1165)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:583)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:533)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:147)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:224)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.pollAndExecCC(ForkJoinPool.java:1190)
	at java.util.concurrent.ForkJoinPool.helpComplete(ForkJoinPool.java:1879)
	at java.util.concurrent.ForkJoinPool.awaitJoin(ForkJoinPool.java:2045)
	at java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:390)
	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:719)
	at java.util.concurrent.ForkJoinPool.invoke(ForkJoinPool.java:2616)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:65)
	at com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:56)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.visitPriorityElementsAndInit(LocalInspectionsPass.java:281)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.inspect(LocalInspectionsPass.java:217)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:118)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:69)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:423)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1170)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:416)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:583)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:533)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:415)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:391)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:147)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:224)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:389)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by mallowigi** [comment]
Yep this should be fixed with the 2.9.1 release

**Comment by jasonhebert** [comment]
Awesome... And thanks for the work and effort y'all put into this project, it's greatly appreciated...

**Comment by nessimabadi** [comment]
Still have the error with the 2.9.1 release

**Comment by mallowigi** [comment]
That's odd... Can you tell me how to reproduce this issue ?

**Comment by nessimabadi** [comment]
Running PHPStorm 2018.2.4
Material Theme Plugin 2.9.1
Windows 10 1809

Did clean install of Material Theme Plugin, still have the font issue.
When checking Appearance & Behavior > Appearance > Override Default fonts the issue is fixed

Got this on the log
`java.lang.NoClassDefFoundError: Could not initialize class com.jetbrains.php.PhpIcons
	at de.espend.idea.laravel.blade.TemplateLineMarker.collectTemplateFileRelatedFiles(TemplateLineMarker.java:227)
	at de.espend.idea.laravel.blade.TemplateLineMarker.collectSlowLineMarkers(TemplateLineMarker.java:72)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.a(LineMarkersPass.java:197)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.a(LineMarkersPass.java:104)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:80)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:91)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:69)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:423)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1161)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:416)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.d(PassExecutorService.java:415)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:391)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:147)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:222)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:389)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)`

![image](https://user-images.githubusercontent.com/11637110/46481239-94d99f00-c7b8-11e8-87ce-d5d0c8fe290c.png)

**Comment by mallowigi** [comment]
Can you print here your list of plugins ?

**Comment by nessimabadi** [comment]
.env files support (0.7)
.ignore (3.0.0.182)
AngularJS (182.4505.42)
ANSI Highlighter (1.2.4)
Apache config (.htaccess) support (182.4505.42)
ASP (0.1)
Behat Support (182.4505.42)
Blade Support (182.4505.42)
Codeception Framework (182.4505.42)
CodeGlance (1.5.4)
CoffeeScript (182.4505.42)
Command Line Tool Support (182.4505.42)
Copyright (8.1)
CSS Support (182.4505.42)
CVS Integration (11)
Database Tools and SQL (182.4505.42)
Docker integration (182.4505.42)
Drupal Support (182.4505.42)
File Watchers (182.4505.42)
Gherkin (999.999)
Git Integration (8.1)
GitHub (182.4505.42)
GNU GetText files support (*.po) (182.4505.42)
Haml (182.4505.42)
HTML Tools (2.0)
HTTP Client (182.4505.42)
hunspell (1.0)
IDE Settings Sync (182.4505.42)
Ideolog (182.0.7.0)
Ini4Idea (182.4505.42)
IntelliLang (8.0)
JavaScript Debugger (1.0)
JavaScript Intention Power Pack (0.9.4)
JavaScript Support (1.0)
Joomla! Support (182.4505.42)
Laravel Plugin (0.15)
Less support (182.4505.42)
Markdown support (182.4505.42)
Material Theme UI (2.9.1)
Mercurial Integration (10.0)
NodeJS (182.4505.42)
Perforce Integration (2.0)
Performance Testing (182.4505.42)
Phing Support (182.4505.42)
PHP composer.json support (1.0.25)
PHP Docker (182.4505.42)
Php Inspections (EA Extended) (3.0.6.1)
PHP Remote Interpreter (182.4505.42)
PHPSpec BDD Framework (182.4505.42)
PhpStorm Workshop (182.4505.42)
Refactor-X (2.01)
Remote Hosts Access (0.1)
ReStructuredText Support (182.4505.42)
Sass support (182.4505.42)
Settings Repository (182.4505.42)
SSH Remote Run (0.1)
Subversion Integration (1.1)
Task Management (1.0)
Terminal (0.1)
TextMate bundles support (182.4505.42)
Time Tracking (1.0)
tslint (182.4505.42)
Twig Support (182.4505.42)
UML Support (1.0)
Vagrant (182.4505.42)
Vue.js (182.4505.42)
W3C Validators (2.0)
WordPress Support (182.4505.42)
XPathView + XSLT Support (4)
XSLT-Debugger (1.4)
YAML (182.4505.42)

**Comment by mallowigi** [comment]
Still can't reproduce. Perhaps you have a project that i can clone and check ?

**Comment by PzYon** [comment]
I had the same issue in WebStorm after the Windows Update. Reinstalling Roboto (as you mentioned) and rebooting the PC solved it. Thanks!

**Comment by alvarezaaronAI** [comment]
Had the same issue, although it got fixed using Roboto Fonts.

Thanks everyone for the Resolution.
